
' This file is used by Code Analysis to maintain SuppressMessage 
' attributes that are applied to this project.
' Project-level suppressions either have no target or are given 
' a specific target and scoped to a namespace, type, member, etc.

<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKretaFunctions.myGETRequest``1(System.String,System.Collections.Generic.Dictionary{System.String,System.String},System.Boolean)~System.Threading.Tasks.Task{``0}")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKreta.myGETRequest``1(System.String,System.Collections.Generic.Dictionary{System.String,System.String},System.Boolean)~System.Threading.Tasks.Task{``0}")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKreta.myPOSTRequest``1(System.String,System.String,System.String,System.Collections.Generic.Dictionary{System.String,System.String})~``0")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKretaFunctions.myPOSTRequest``1(System.String,System.String,System.String,System.Collections.Generic.Dictionary{System.String,System.String})~``0")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKreta.downloadFile(HF_Scraper.eKretaStructures.Fajl,System.String)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKreta.getAccessToken~System.String")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKreta.getMessageByID(System.UInt64)~System.Threading.Tasks.Task{HF_Scraper.eKretaStructures.Message}")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKreta.getMessageByIDPrivate(System.UInt64,System.String)~System.Threading.Tasks.Task{HF_Scraper.eKretaStructures.Message}")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKreta.getMessageByIDUpdate(System.UInt64)~System.Threading.Tasks.Task{HF_Scraper.eKretaStructures.Message}")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKreta.getMessageRange(System.DateTime,System.DateTime)~System.Threading.Tasks.Task{System.Collections.Generic.List{HF_Scraper.eKretaStructures.Message}}")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKreta.getMessages~System.Threading.Tasks.Task{System.Collections.Generic.List{HF_Scraper.eKretaStructures.Message}}")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKreta.getMessagesPrivate(System.String)~System.Threading.Tasks.Task{System.Collections.Generic.List{HF_Scraper.eKretaStructures.Message}}")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKreta.getMessagesUpdate~System.Threading.Tasks.Task{System.Collections.Generic.List{HF_Scraper.eKretaStructures.Message}}")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKreta.getNewAccessToken(System.String,System.String,System.String)~System.String")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKreta.getNewAccessToken(System.String,System.String,System.String,System.String)~System.String")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKretaFunctions.downloadFile(HF_Scraper.eKretaStructures.Fajl,System.String,System.String)~System.Threading.Tasks.Task")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKretaFunctions.formatHomeworkResponse(HF_Scraper.eKretaFunctions.TeacherHomeworkResponse,System.Collections.Generic.List{HF_Scraper.eKretaFunctions.StudentHomeworkResponse})~System.Object")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKretaFunctions.getAccessToken(System.String,System.String)~System.String")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKretaFunctions.getHomework(System.String,System.UInt64,System.String)~System.Threading.Tasks.Task{HF_Scraper.eKretaStructures.Homework}")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKretaFunctions.getHomeworkList(System.String,System.String,System.String,System.String)~System.Threading.Tasks.Task{System.Collections.Generic.List{HF_Scraper.eKretaStructures.Homework}}")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKretaFunctions.getInstituteFromID(System.Int64)~System.Threading.Tasks.Task{HF_Scraper.eKretaStructures.Institute}")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKretaFunctions.getInstituteList~System.Threading.Tasks.Task{System.Collections.Generic.List{HF_Scraper.eKretaStructures.Institute}}")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKretaFunctions.getLessonList(System.String,System.String,System.String,System.String)~System.Threading.Tasks.Task{System.Collections.Generic.List{HF_Scraper.eKretaStructures.Lesson}}")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKretaFunctions.getNewAccessToken(System.String,System.String,System.String)~System.String")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKretaFunctions.getNewAccessToken(System.String,System.String,System.String,System.String)~System.String")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKretaFunctions.getRegistry(System.String)~System.Object")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKretaFunctions.sendStudentHomework(System.String,HF_Scraper.eKretaStructures.Homework,System.String,System.String)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:HF_Scraper.eKretaFunctions.setRegistry(System.String,System.Object,Microsoft.Win32.RegistryValueKind)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="type", Target:="~T:HF_Scraper.eKreta")>